### PR TITLE
Add resolvconf::tail to allow /etc/resolvconf/resolv.conf.d/tail file management

### PR DESCRIPTION
**Pull request by pataquets**
The file /etc/resolvconf/resolv.conf.d/tail has the same structure and syntax than /etc/resolv.conf, so I've added a "file" parameter to resolvconf class (defaulting to previous hardcoded value) to allow the resolvconf::tail class to be based on it. This way, future enhancements to resolvoconf will benefit to depending tail class.
As it is now, the only caveat is that both are mutually exclusive due to tail defining again resolvconf base class, but since the use case is meant for OS-managed resolv.conf files as in Ubuntu, it should not break anything. The specific purpose of the tail file is to allow changes/appends to an already OS-managed resolv.conf file.
Another solution would be redefine resolvconf as a resource instead of a class, but that's going too far and maybe unnecessary due to tail file purpose.
Tested working successfully under Ubuntu Precise. Managed hosts do not have any resolv.conf file managed, just the tail file.

More info:
http://manpages.ubuntu.com/manpages/precise/man8/resolvconf.8.html#contenttoc7
http://askubuntu.com/questions/130452/how-do-i-add-a-dns-server-via-resolv-conf

### CODE REVIEW

**Comment by pataquets** [comment]
Since I'm also managing "server=" entries in the tail file, I plan to add the "server" parameter later to base resolvconf class.

**Comment by thias** [comment]
OK, after reading the links, I see where you're going with this (since I don't use Ubuntu myself), but your changes are wrong.
First, you are duplicating code which should be avoided. Why not just set this in hiera once you add support for the file parameter? (no need for a 2nd class)

``` yaml
---
resolvconf::file: '/etc/resolvconf/resolv.conf.d/tail'
```

Second, if you create `resolvconf::tail` then it needs to go into its own `manifests/tail.pp` file.

Maybe the best approach would be to create `resolvconf::file` as a definition, which would be called from the main class, but would also let people use it for other files, such as the tail one you need, but also others.

**Comment by pataquets** [comment]
Hi thias.
If I understood well, you are suggesting to just add the $file parameter and pull the tail file by directly calling resolvconf class. I agree it's also a better idea, since it needs less code to maintain. In fact, a resolvconf::tail would only be a shortcut convenience. It's OK for me, too.
It also has more sense, since I've discovered that there is also a "head" resolvconf file.
What makes me doubt is if the tail file accepts _all_ the same parameters that the main resolv.conf file does. If that was not the case, the resolvconf::tail class would make sense to restrict the parameters only to the tail's supported ones. Looks like they are both the same, I haven't found any difference on the docs, so I'll assume it's OK.

So, in case you don't have any further knowledge that confirms/contradicts the above doubt, I'm on it for a base resolvconf::file class with an extra "file" parmeter, and use it from everywhere it's needed, including main "resolvconf". How would you split the files? Both resolvocnf and resolvconf::file in init.pp?
Thanks.

**Comment by thias** [comment]
If you only intend to manage a single file, such as the tail one, there is no need to add a definition and you can just add the `$file` parameter to the main class like you already did.

If you intend to manage multiple files, such as tail and head, then it's best to move the current code to become a definition, and change the current class to wrap around it with `/etc/resolv.conf` as the `$title`.

Does that make more sense?

**Comment by pataquets** [comment]
Moving the current code to a definition (resolvconf::file)+adding a file param makes sense to me the most.
Adding resolconf::head/tail classes looks optional, just a convenience, maybe to avoid anyone shooting their feet when managing head and tail files.
Going to make it a definition. Do you think adding ::head and ::tail classes makes sense? It does, IMO. Just make everyone use resolvconf, resolvconf::head and resolvconf::tail and you won't be able to define none of them twice by accident.

**Comment by thias** [comment]
Grouping a class and a definition inside a single file is wrong. Still, I think I understood what you wanted, so please have a look at e00267d4471212cb33b489824022deb2b1c4501f and let me know if that works for you. If it doesn't, just reopen this issue.

**Comment by pataquets** [comment]
I tested the code you commited and it works great, thanks. The only thing I miss is an ensure parameter I was using to force DNS server priorities by juggling with head and tail files. I've sent a separate PR.
Are you interested in me submitting convenience classes for ::head and ::tail as explained in my previous comment? (in separate files)

**Pull request closed without merging**
